package com.masirg.orientation;

public class  C {
    public static final String NOTIFICATION_CHANNEL_1 = "NOTIFICATION_CHANNEL_1";

    //OrientationService intents
    public static final String ORIENTATION_SERVICE_INTENT_LOCATION_UPDATE = "ORIENTATION_SERVICE_INTENT_LOCATION_UPDATE";
    public static final String ORIENTATION_SERVICE_INTENT_BACKGROUND_LOCATIONS_UPDATE = "ORIENTATION_SERVICE_INTENT_BACKGROUND_LOCATIONS_UPDATE";
    public static final String ORIENTATION_SERVICE_INTENT_NEW_CHECKPOINT = "ORIENTATION_SERVICE_INTENT_NEW_CHECKPOINT";
    public static final String ORIENTATION_SERVICE_INTENT_NEW_WAYPOINT = "ORIENTATION_SERVICE_INTENT_NEW_WAYPOINT";
    public static final String ORIENTATION_SERVICE_INTENT_STATS_UPDATE = "ORIENTATION_SERVICE_INTENT_STATS_UPDATE";

    //MapsActivity intents

    public static final String MAPS_ACTIVITY_INTENT_COLLECT_IN_BACKGROUND = "MAPS_ACTIVITY_INTENT_COLLECT_IN_BACKGROUND";
    public static final String MAPS_ACTIVITY_INTENT_STOP_COLLECT_IN_BACKGROUND = "MAPS_ACTIVITY_INTENT_STOP_COLLECT_IN_BACKGROUND";
    public static final String MAPS_ACTIVITY_INTENT_ADD_CHECKPOINT = "MAPS_ACTIVITY_INTENT_ADD_CHECKPOINT";
    public static final String MAPS_ACTIVITY_INTENT_ADD_WAYPOINT = "MAPS_ACTIVITY_INTENT_ADD_WAYPOINT";

    //OrientationService intent extras
    public static final String ORIENTATION_SERVICE_LATITUDE = "ORIENTATION_SERVICE_LATITUDE";
    public static final String ORIENTATION_SERVICE_LONGITUDE = "ORIENTATION_SERVICE_LONGITUDE";
    public static final String ORIENTATION_SERVICE_LATITUDES = "ORIENTATION_SERVICE_LATITUDES";
    public static final String ORIENTATION_SERVICE_LONGITUDES = "ORIENTATION_SERVICE_LONGITUDES";

    public static final String ORIENTATION_SERVICE_TOTAL_DISTANCE = "ORIENTATION_SERVICE_TOTAL_DISTANCE";
    public static final String ORIENTATION_SERVICE_TOTAL_TIME = "ORIENTATION_SERVICE_TOTAL_TIME";
    public static final String ORIENTATION_SERVICE_CHECKPOINT_DISTANCE = "ORIENTATION_SERVICE_CHECKPOINT_DISTANCE";
    public static final String ORIENTATION_SERVICE_CHECKPOINT_DIRECT_DISTANCE = "ORIENTATION_SERVICE_CHECKPOINT_DIRECT_DISTANCE";
    public static final String ORIENTATION_SERVICE_CHECKPOINT_TIME = "ORIENTATION_SERVICE_CHECKPOINT_TIME";
    public static final String ORIENTATION_SERVICE_WAYPOINT_DISTANCE = "ORIENTATION_SERVICE_WAYPOINT_DISTANCE";
    public static final String ORIENTATION_SERVICE_WAYPOINT_DIRECT_DISTANCE = "ORIENTATION_SERVICE_WAYPOINT_DIRECT_DISTANCE";
    public static final String ORIENTATION_SERVICE_WAYPOINT_TIME = "ORIENTATION_SERVICE_WAYPOINT_TIME";


    //Instance state constants
    public static final String INSTANCE_STATE_SERVICE_STARTED = "INSTANCE_STATE_SERVICE_STARTED";
    public static final String INSTANCE_STATE_LOCATIONS_LATITUDES = "INSTANCE_STATE_LOCATIONS_LATITUDES";
    public static final String INSTANCE_STATE_LOCATIONS_LONGITUDES = "INSTANCE_STATE_LOCATIONS_LONGITUDES";
    public static final String INSTANCE_STATE_CHECKPOINT_LOCATIONS_LATITUDES = "INSTANCE_STATE_CHECKPOINT_LOCATIONS_LATITUDES";
    public static final String INSTANCE_STATE_CHECKPOINT_LOCATIONS_LONGITUDES = "INSTANCE_STATE_CHECKPOINT_LOCATIONS_LONGITUDES";
    public static final String INSTANCE_STATE_WAYPOINT_LATITUDE = "INSTANCE_STATE_WAYPOINT_LATITUDE";
    public static final String INSTANCE_STATE_WAYPOINT_LONGITUDE = "INSTANCE_STATE_WAYPOINT_LONGITUDE";

    public static final String INSTANCE_STATE_TOTAL_TIME = "INSTANCE_STATE_TOTAL_TIME";
    public static final String INSTANCE_STATE_WAYPOINT_DIRECT_DISTANCE = "INSTANCE_STATE_WAYPOINT_DIRECT_DISTANCE";
    public static final String INSTANCE_STATE_WAYPOINT_DISTANCE = "INSTANCE_STATE_WAYPOINT_DISTANCE";
    public static final String INSTANCE_STATE_WAYPOINT_TIME = "INSTANCE_STATE_WAYPOINT_TIME";
    public static final String INSTANCE_STATE_CHECKPOINT_TIME = "INSTANCE_STATE_CHECKPOINT_TIME";
    public static final String INSTANCE_STATE_CHECKPOINT_DIRECT_DISTANCE = "INSTANCE_STATE_CHECKPOINT_DIRECT_DISTANCE";
    public static final String INSTANCE_STATE_CHECKPOINT_DISTANCE = "INSTANCE_STATE_CHECKPOINT_DISTANCE";
    public static final String INSTANCE_STATE_TOTAL_DISTANCE = "INSTANCE_STATE_TOTAL_DISTANCE";

    public static final String TRACK_ID = "TRACK_ID";
    public static final String START_OLD_TRACK_ACTIVITY_BUNDLE = "START_OLD_TRACK_ACTIVITY_BUNDLE";
}
